[package]
name = "cvars"
version = "0.1.0"
edition = "2021"

include = ["tests/**"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc = { path = "proc" }
